# Generated by Django 4.1 on 2023-04-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_about_course_details_instructors_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='about_model',
        ),
    ]
