# Generated by Django 4.1 on 2023-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_rename_about_about_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_description_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item', models.CharField(max_length=100)),
                ('course', models.ManyToManyField(to='webApp.course_details')),
            ],
        ),
    ]
