# Generated by Django 4.1 on 2023-04-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_enquiry_course_details_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_details',
            old_name='url',
            new_name='course_url',
        ),
    ]
