# Generated by Django 4.1 on 2023-04-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0009_rename_url_course_details_course_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='course_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
