# Generated by Django 4.1 on 2023-04-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0010_alter_course_details_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_details',
            name='course_url',
        ),
    ]
